### ISSUE TITLE
MosaicViews v0.2.0

### ISSUE THREAD

**Issue by johnnychen94** [JuliaArrays/MosaicViews.jl#10]
MosaicViews v0.1 only covers basic need of machine learning visualization tasks, i.e., preview the dataset.

MosaicViews v0.2.0 is a functionality release to ease visualization tasks further so that we can use this in daily image processing work, here's something I have in mind that should exist:

- [x] support multiple images as inputs #6 #8 
- [x] center shift padded images #9 
~- [ ] by default, make the squarest mosaic view #3~ (Edit: this would break some of existing pipeline, so not ready for this release)
- [x] support 1d/2d image inputs #13

As for documentation, README isn't very illustrative for the purpose of this package, and this package is quite small that setting up an independent gh-page adds more maintenance work, which I don't like, so I plan to just add a demo page in JuliaImages side to give more examples.

After v0.2.0 release, I plan to let ImageShow reexport this package, which IMO is the conceptually right place for this package to get into JuliaImages ecosystem (cc @timholy )

After reexporting this package in ImageShow, we can give a specialization for transparent colors as `fillvalue`. The current behavior is to convert `fillvalue` to `eltype(img1)`, which means the following code doesn't really fill a transparent color, but indeed, fill a black pixel. The specialization will be on `sym_paddedviews` and `paddedviews`.

```julia
mosaicview(img1, img2; fillvalue=AGray(0, 0))
```

**Comment by johnnychen94** [comment]
@Evizero If it's not installed, could you install the [registrator](https://github.com/JuliaRegistries/Registrator.jl) for this package?
